-- =====================================================
-- youthportal (청년정책포탈) 스키마
-- 대상: Oracle Database XE (18c/21c 기준, IDENTITY 컬럼 사용)
-- 실행 방법: SQL*Plus / SQL Developer 등에서 scott 계정으로 접속 후 1회 수동 실행
--           (스프링 부트가 자동으로 실행하지 않음 - 재시작마다 재실행되어
--            기존 데이터와 충돌하는 것을 막기 위해 의도적으로 자동 실행 대상에서 제외함)
-- =====================================================

-- -----------------------------------------------------
-- 회원 테이블
-- -----------------------------------------------------
CREATE TABLE USERS (
  USER_ID         VARCHAR2(50)   NOT NULL,                         -- 회원 아이디 (기본키, 카카오 회원은 "kakao_"+카카오ID)
  UPW             VARCHAR2(200)  NOT NULL,                         -- 비밀번호 (BCrypt 해시로 저장, 카카오 회원은 로그인에 쓰이지 않는 랜덤값)
  NAME            VARCHAR2(50)   NOT NULL,                         -- 이름
  BIRTH_DATE      VARCHAR2(8),                                     -- 생년월일 (yyyyMMdd 문자열, 카카오 회원은 기본 동의항목에 없어 NULL 가능)
  PHONE           VARCHAR2(20),                                    -- 휴대폰 번호
  REG_DATE        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,     -- 가입일시
  ROLE            NUMBER(1)      DEFAULT 0 NOT NULL CHECK (ROLE IN (0,1)),           -- 0=일반회원, 1=관리자
  DEL             NUMBER(1)      DEFAULT 0 NOT NULL CHECK (DEL IN (0,1)),            -- 0=정상, 1=탈퇴
  FAIL_COUNT      NUMBER(3)      DEFAULT 0 NOT NULL,                -- 로그인 실패 누적 횟수
  ACCOUNT_LOCKED  NUMBER(1)      DEFAULT 0 NOT NULL CHECK (ACCOUNT_LOCKED IN (0,1)), -- 0=정상, 1=잠김
  SOCIAL_TYPE     VARCHAR2(20),                                    -- NULL=일반가입, 'KAKAO'=카카오 로그인
  SOCIAL_ID       VARCHAR2(100),                                   -- 소셜 로그인 제공자가 발급한 회원 고유번호
  CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
  CONSTRAINT UQ_USERS_SOCIAL_ID UNIQUE (SOCIAL_ID)                  -- 같은 소셜 계정이 중복 연동되지 않도록 방지 (NULL은 여러 개 허용)
);

-- -----------------------------------------------------
-- 청년정책 테이블
-- -----------------------------------------------------
CREATE TABLE POLICY (
  PNO         NUMBER         GENERATED BY DEFAULT AS IDENTITY,      -- 정책 번호 (기본키, 자동채번)
  -- ↓ Oracle 11g 등 IDENTITY 미지원 버전이라면 위 줄 대신 "PNO NUMBER,"로 바꾸고
  --   별도 시퀀스(SEQ_POLICY) + BEFORE INSERT 트리거로 채번해야 함
  SOURCE_ID   VARCHAR2(50),                                         -- 정책 출처 ID (온통청년 API의 plcyNo, 중복 가져오기 방지용)
  TITLE       VARCHAR2(200)  NOT NULL,                              -- 정책 제목
  CONTENT     CLOB           NOT NULL,                              -- 정책 내용(본문)
  CATEGORY    VARCHAR2(200)  NOT NULL,                              -- 정책 분류 (온통청년 API의 분류명 길이가 생각보다 길 수 있어 넉넉하게 잡음)
  REGION      VARCHAR2(100),                                        -- 지역구명 (온통청년 API의 주관기관명)
  TARGET_AGE  VARCHAR2(50),                                         -- 지원 대상 연령
  START_DATE  DATE,                                                 -- 사업 시작일
  END_DATE    DATE,                                                 -- 사업 종료일
  APPLY_START_DATE DATE,                                            -- 신청 시작일 ("마감" 여부는 사업기간이 아니라 이 신청기간 기준으로 판단)
  APPLY_END_DATE   DATE,                                            -- 신청 마감일
  REG_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,          -- 등록일시
  CONSTRAINT PK_POLICY PRIMARY KEY (PNO),
  CONSTRAINT UQ_POLICY_SOURCE_ID UNIQUE (SOURCE_ID)                  -- 같은 외부 정책이 두 번 저장되지 않도록 방지
);

-- -----------------------------------------------------
-- 정책 신청 테이블
-- -----------------------------------------------------
CREATE TABLE APPLICATION (
  APP_NO         NUMBER        GENERATED BY DEFAULT AS IDENTITY,    -- 신청 번호 (기본키, 자동채번)
  -- ↓ 11g 대체안: "APP_NO NUMBER,"로 바꾸고 SEQ_APPLICATION 시퀀스 + 트리거 사용
  PNO            NUMBER        NOT NULL,                            -- 신청한 정책 번호 (외래키)
  USER_ID        VARCHAR2(50)  NOT NULL,                            -- 신청한 회원 아이디 (외래키)
  REASON         VARCHAR2(1000),                                    -- 신청 사유
  STATUS         VARCHAR2(20)  DEFAULT '접수중' NOT NULL
                 CHECK (STATUS IN ('접수중','승인','반려','취소')),   -- 신청 상태 (관리자 심사 상태)
  APPLY_DATE     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,        -- 신청일시
  UPDATE_DATE    TIMESTAMP,                                         -- 상태 변경일시
  FORWARD_STATUS  VARCHAR2(20)                                      -- 관할 기관 전달 상태 (NULL=미전송). 심사 상태(STATUS)와는 별개 개념
                 CHECK (FORWARD_STATUS IN ('전송완료','전송실패','수동처리대기')),
  FORWARD_MESSAGE VARCHAR2(500),                                    -- 전달 결과 메시지 (접수번호 또는 실패/안내 사유)
  FORWARD_DATE    TIMESTAMP,                                        -- 전달 처리일시
  CONSTRAINT PK_APPLICATION PRIMARY KEY (APP_NO),
  CONSTRAINT FK_APP_POLICY FOREIGN KEY (PNO) REFERENCES POLICY(PNO),
  CONSTRAINT FK_APP_USER   FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
  -- ON DELETE CASCADE를 주지 않음: 정책을 삭제할 때 신청 내역이 있으면
  -- FK 위반으로 실패시켜 신청 이력이 조용히 사라지지 않도록 함 (서비스 계층에서 안내 메시지로 변환)
);

-- -----------------------------------------------------
-- 신청 첨부파일 테이블 (신청 1건에 파일 여러 개를 붙일 수 있도록 1:N으로 분리)
-- -----------------------------------------------------
CREATE TABLE APPLICATION_FILE (
  FILE_NO        NUMBER         GENERATED BY DEFAULT AS IDENTITY,   -- 파일 번호 (기본키, 자동채번)
  APP_NO         NUMBER         NOT NULL,                           -- 소속 신청 번호 (외래키)
  SAVED_NAME     VARCHAR2(300)  NOT NULL,                           -- 서버 저장 파일명 (UUID_원본명)
  ORIGINAL_NAME  VARCHAR2(300)  NOT NULL,                           -- 업로드 당시 원본 파일명 (다운로드 시 노출)
  UPLOAD_DATE    TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,       -- 업로드일시
  CONSTRAINT PK_APPLICATION_FILE PRIMARY KEY (FILE_NO),
  CONSTRAINT FK_FILE_APPLICATION FOREIGN KEY (APP_NO) REFERENCES APPLICATION(APP_NO)
);

-- 조회 성능을 위한 인덱스
CREATE INDEX IDX_APPLICATION_USER ON APPLICATION(USER_ID);
CREATE INDEX IDX_APPLICATION_PNO  ON APPLICATION(PNO);
CREATE INDEX IDX_POLICY_CATEGORY  ON POLICY(CATEGORY);
CREATE INDEX IDX_APPLICATION_FILE_APPNO ON APPLICATION_FILE(APP_NO);

-- -----------------------------------------------------
-- 참고: 최초 관리자 계정 만들기
-- 1) 애플리케이션의 /user/join 화면에서 일반 회원으로 먼저 가입한다.
-- 2) 아래 SQL로 해당 계정을 관리자로 승격한다. ('본인아이디' 부분을 실제 가입한 아이디로 교체)
-- -----------------------------------------------------
-- UPDATE USERS SET ROLE = 1 WHERE USER_ID = '본인아이디';
-- COMMIT;
